### ISSUE TITLE
non-optimal memory layout for chunkerConfig struct

### ISSUE THREAD

**Issue by mappu** [restic/chunker#10]
Hi,

The tool https://github.com/mdempsky/maligned reports: `restic/chunker/chunker.go:70:20: struct of size 4160 could be 4152`

Reduced memory would be helpful for Restic. But i don't know if there's a performance impact.

**Comment by fd0** [comment]
Thanks for taking a look. As far as I understood the output of the tool, it reports that by reordering the entries in the struct it can be reduced by 8 bytes. This is not significant for us, since that struct only exists once per chunker, and we only have a few (~10 or so) chunkers in parallel. And it does not help to decrease the memory usage at all.
