### ISSUE TITLE
Inserting 1 at the beginning of the hashed data

### ISSUE THREAD

**Issue by green-coder** [restic/chunker#9]
Hi,

I think that it is not useful to insert `1` at the beginning of the hashed data when we are using the Rabin hash as a rolling hash.

Probably, the intent of this prefix is to make the number of leading zeroes in the data to be hashed counted : because zeroes hash to zero, without the `1` prefix,  `[42]` would hash to the same as  `[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 42]`.

**Comment by fd0** [comment]
Ah, I've only just seen this issue, thanks for opening it. Discussing things in comments to commits is not a good idea, these tend to get lost.

I'm pretty sure you're right, but any changes to the chunker algorithm must be made carefully so that the behavior (splits) does not change. The main application for this package is the [restic backup program](https://restic.github.io) so I won't approve breaking behavior lightly.

If you like, can you open a PR that removes shifting in the `1` to see whether the tests still pass? Maybe add a few more tests for corner cases like this?

**Comment by green-coder** [comment]
I think that the `1` which is inserted in the window during the Reset() has his influence removed from the hash as soon as it is pushed out of the window by other data : exactly after `n` bytes, `n` being the size of the window.

The behavior of your chunker will be unchanged if the minimum block size of the chunker is set to be at least the size of the window (and I believe it is the case).

**Comment by fd0** [comment]
I agree. And `MinSize` is much larger than the window size of 64 byte.

**Comment by fd0** [comment]
So, are you still interested in this issue? Otherwise I'll just close it.

**Comment by green-coder** [comment]
We can close it.
